---
title: "Regression Assignment"
author: "Student Name"
date: "10/4/2024"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# Practice

copy and paste your work by following each example from the lab manual for this exercise

```{r}
rm(list = setdiff(ls(), lsf.str()))
setwd("~/Dropbox/IIITH_Teaching/BRSM2023/R_Labs") # change this to your working directory where you've put the data files, etc for this session
setwd("~/Desktop/Work/BRSM_SP23/Lab")

# Simulate data y <- b1x1 + b2x2 + b0 with Normally distributed residuals. You can assume sensible values for b1 b2 b0 as you please. 
dat<-read.csv("housing.csv")
houselm <- lm(dat$median_house_value ~ dat$total_rooms + dat$median_income)

summary(houselm)

```

```{r}
# Binary 
mydata<-read.csv("binary.csv")
mydata$rank <- factor(mydata$rank)
fit <- glm(admit ~ gre + gpa + rank, data = mydata, family = "binomial")

summary(fit) # display results
confint(fit) # 95% CI for the coefficients
exp(coef(fit)) # exponentiated coefficients
exp(confint(fit)) # 95% CI for exponentiated coefficients
predict(fit, type="response") # predicted values
residuals(fit, type="deviance") # residuals

```


```{r}

 


```
```{r}

```


```{r}

 
```




# Assignment 4 exercises

use the code from above to attempt to solve the extra things we ask you do for this assignment

```{r}



```
# Written answers


Write your answer here.

